### ISSUE TITLE
Docs required for special_address in metallb component

### ISSUE THREAD

**Issue by knrt10** [kinvolk/lokomotive#632]
Currenly in [configuration example](https://github.com/kinvolk/lokomotive/blob/master/docs/configuration-reference/components/metallb.md#configuration) we are showing use for `special_addresses` but there is not refrence to it in [attribute-reference](https://github.com/kinvolk/lokomotive/blob/master/docs/configuration-reference/components/metallb.md#attribute-reference) table. We need to document it.

**Comment by knrt10** [comment]
Can we say this is fixed by https://github.com/kinvolk/lokomotive/commit/173e517e482b964dfd943316971e4294b1723e41#diff-32657cb248d48ce75b8dd96cac5450b3R88?

**Comment by invidian** [comment]
Personally, I still do not understand what this option is doing and how to use it, so I'd say we should improve that still.

**Comment by knrt10** [comment]
@ipochi @surajssd any ideas?

**Comment by ipochi** [comment]
I think thats a map key/value field. Doesn't have any special meaning to it.

**Comment by invidian** [comment]
To rephrase, as a user, under what conditions I should care to set `special_addresses` to something? And to what?

**Comment by ipochi** [comment]
@johananl Does having the key `default` or `special_addresses` carry a special meaning in `metallb` ?

**Comment by johananl** [comment]
Nope, these are likely sample address pool *names*.

**Comment by johananl** [comment]
If these names are confusing, please feel free to change them to something more intuitive.

**Comment by johananl** [comment]
Fixed in https://github.com/kinvolk/lokomotive/pull/996.
